version: 0.2

phases:
  pre_build:
    commands:
      - echo Entering the reactapp/backend directory
      - cd balloon-reactapp/backend
      - echo Installing backend dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Running server...
      - node server.js

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: balloon-reactapp/backend
